# Generated by Django 3.1.5 on 2021-05-24 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_todoform_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoform',
            old_name='name',
            new_name='tittle',
        ),
        migrations.AlterField(
            model_name='todoform',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
